#!/bin/bash

# Disk /dev/sdc: 8 TiB, 8796093022208 bytes, 2147483648 sectors
# Disk /dev/sdg: 2 TiB, 2199023255552 bytes, 536870912 sectors
# Disk /dev/sdf: 1 TiB, 1099511627776 bytes, 268435456 sectors
# Disk /dev/sde: 512 GiB, 549755813888 bytes, 134217728 sectors
# Disk /dev/sdd: 256 GiB, 274877906944 bytes, 67108864 sectors

function fio_test() {
    fio -filename=$1 -direct=1  \
    -ioengine=libaio \
    -iodepth=1 \
    -rw=randrw \
    -rwmixwrite=50 \
    -bs=$2 \
    -numjobs=1 \
    -runtime=120 \
    -time_based \
    -group_reporting \
    -name=test_rw
}

## Test 256G

# Test 8T
#for n in 32k 64k 128k; do
#	fio_test /dev/sdc ${n} | tee fio.${n}.8t
#done

## Test 2T
#for n in 32k 64k 128k; do
#	fio_test /dev/sdg ${n} | tee fio.${n}.2t
#done
#
## Test 1T
#for n in 32k 64k 128k; do
#	fio_test /dev/sdf ${n} | tee fio.${n}.1t
#done
#
## Test 512G
#for n in 32k 64k 128k; do
#	fio_test /dev/sde ${n} | tee fio.${n}.512g
#done
#
## Test 256G
#for n in 32k 64k 128k; do
#	fio_test /dev/sdd ${n} | tee fio.${n}.256g
#done
#
